### ISSUE TITLE
Add support for scarthgap

### ISSUE THREAD

**Issue by parthitce** [menschel-d/meta-barebox#7]
`scarthgap` which is Yocto 5.0 is released. Am not sure if there is a way to open a PR with new branch creation in github. 
@menschel-d Is it possible to branch `scarthgap` based on current `master`?

**Comment by menschel-d** [comment]
@parthitce Thank you for the reminder. I've added new branch for `scarthgap`, updated barebox to 2024.04.0 and successfully tested the build process for an old Raspberry Pi 2.
